// <auto-generated />
namespace Movie_Rental_Store.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class AddDateofBirthToCustomersModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddDateofBirthToCustomersModel));
        
        string IMigrationMetadata.Id
        {
            get { return "202408101824589_AddDateofBirthToCustomersModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
